site_name: perl-cross
site_description: Cross-compiling perl
site_author: Alex Suykov
repo_url: https://github.com/arsv/perl-cross

pages:
- Intro: index.md
- Download: download.md
- Usage: usage.md
- Design: design.md
- Modules: modules.md
- Hints: hints.md
- Testing: testing.md

markdown_extensions:
- admonition
- def_list
theme: mkdocs
